### ISSUE TITLE
Filebrowser properties inconsistent

### ISSUE THREAD

**Issue by elvece** [Start9Labs/filebrowser-wrapper#19]
There has been at least one report of inconsistencies in the migration for properties (`stats.yaml` file). The problem has expressed as _some_ properties not being displayed in the UI. In the reported case (by Lex), the password was not displaying, despite it coming back in the backend response. 

<img width="1680" alt="Screen Shot 2022-01-31 at 5 32 19 PM" src="https://user-images.githubusercontent.com/12953208/152841389-d8f1ce08-8af5-49bd-a985-e02ad069d894.png">

Backend response:
```
{
	"jsonrpc": "2.0",
	"result": {
		"version": 1,
		"data": [
			{
				"name": "Default Username",
				"value": "admin",
				"description": "This is your default username. While it is not necessary, you may change it inside your File Browser web application. That change, however, will not be reflected here. If you change your default username and forget your new username, there is no way to regain access.",
				"copyable": true,
				"qr": false
			},
			{
				"name": "Default Password",
				"value": "<redacted>,
				"description": "This is your randomly-generated, default password. While it is not necessary, you may change it inside your File Browser web application. That change, however, will not be reflected here. If you change your default password and forget your new password, there is no way to regain access.",
				"copyable": true,
				"masked": true,
				"qr": false
			}
		]
	},
	"id": null
}
```

Context:
Filebrowser on 02x had v1 properties, this standard was persisted for 030. An example of v1 properties that were successfully migrated looks like this:

```
root@embassy-65f56cab:~# cat /embassy-data/package-data/volumes/filebrowser/data/main/start9/stats.yaml
version: 1
data:
  - name: Default Username
    value: admin
    description: ~
    copyable: true
    qr: false
  - name: Default Password
    value: "bCbTIbcFTzaQVoRp"
    description: ~
    copyable: true
    qr: false
```

Problem:
I think the problem lies in the extra attribute of `masked: true` within Lex's migrated properties. I am not sure how Lex got into this state. I have confirmed that by adding this extra property in my migrated 02x config (the one provided above), it fails to display the password in the UI as Lex is experiencing.

Solution:

I see two possible solutions:

1. Ensure that extra properties are ignored in when parsing v1 properties so that all attributes can successfully be displayed
2. Write a developer migration in Filebrowser to migrate the v1 properties to v2 properties so this issue wont exist
